(defparameter *person-id* -1)
(defparameter *path*    (make-pathname :name "Saves/Persons.save"))
(defparameter *persons* (make-array 0  :fill-pointer 0 :adjustable t))

(defun done (x)
  (case x
    (1 (format t "~%Done!"))
    (2 (format t "Loading base...~%"))
    (3 (format t "Loading Person Class...~%"))
    (4 (format t "Loading Saver Functions...~%"))
    (5 (format t "Loading Loader...~%"))
    (6 (format t "Loading Saves...~%"))
    (7 (format t "Loading Classes...~%"))))

(done 2)
(load "User-Function-Macro.lisp")
(load "Core/Support-Functions.lisp")
(done 7)
(load "Core/Classes.lisp")
(done 3)
(load "Core/Person.lisp")
(done 4)
(load "Save-Persons.lisp")
(done 5)
(load "Load-Person.lisp")
(done 6)
(load-persons)
