(defparameter *person-id* -1)
(defparameter *path*    (make-pathname :name "e:/Common Lisp/Person/Persons.save"))
(defparameter *persons* (make-array 0  :fill-pointer 0 :adjustable t))

(defun done (x)
  (case x
    (1 (format t "~%Done!"))
    (2 (format t "Loading base...~%"))
    (3 (format t "Loading Person Class...~%"))
    (4 (format t "Loading Saver Functions...~%"))
    (5 (format t "Loading Loader...~%"))
    (6 (format t "Loading Saves...~%"))
    (7 (format t "Loading Classes...~%"))))

(done 2)
(load "E:/Common Lisp/User-Function-Macro.cl")
(done 7)
(load "E:/Common Lisp/Person/Classes.lisp")
(done 3)
(load "E:/Common Lisp/Person/Person.lisp")
(done 4)
(load "E:/Common Lisp/Person/Save-Persons.lisp")
(done 5)
(load "E:/Common Lisp/Person/Load-Person.lisp")
(done 6)
(load-persons)
